### ISSUE TITLE
Feature request: allow opening the quickfix or location list without focusing on it

### ISSUE THREAD

**Issue by devth** [fszymanski/ListToggle.vim#1]
(nice fork btw)

**Comment by fszymanski** [comment]
I can open/close the quickfix or location list no matter which window I am focused on (I'm using nvim HEAD). Can you elaborate? I'm not sure I understand.

**Comment by devth** [comment]
Yep, I meant I don't want the cursor to jump into the quickfix window when opening. I'd like to be able to toggle it open/close without my cursor moving.

**Comment by fszymanski** [comment]
Now I understand, that's a really good idea. Maybe it would be good to add a new global option `g:listtoggle_jump_to_window` or something like this. What do you think? Anyway, if I find some free time tonight or tomorrow I will try to add this feature.

**Comment by devth** [comment]
Sounds good to me!
